# Generated by Django 4.1.2 on 2022-10-19 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
