# Generated by Django 4.1.2 on 2022-10-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0002_book_date_created_book_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="date_created",
        ),
    ]
