# Generated by Django 4.1.2 on 2022-10-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0006_alter_genre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
