# Generated by Django 4.1.2 on 2022-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0009_alter_book_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergenre",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="read_status",
            field=models.CharField(
                choices=[("R", "Read"), ("U", "Unread"), ("T", "Trash")],
                default="T",
                max_length=24,
            ),
        ),
    ]
