# Generated by Django 4.1.2 on 2022-10-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0010_usergenre_likes_alter_bookshelf_read_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookgenre",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="bookgenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="bookshelf",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="bookshelf",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="usergenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="usergenre",
            old_name="user_id",
            new_name="user",
        ),
    ]
