# Generated by Django 4.1.2 on 2022-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0011_rename_book_id_bookgenre_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
