# Generated by Django 4.1.2 on 2022-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0012_alter_book_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergenre",
            name="likes",
            field=models.IntegerField(default=1),
        ),
    ]
