# Generated by Django 4.1.2 on 2022-11-06 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookSwiping", "0013_alter_usergenre_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("NB", "Non-Binary")],
                        max_length=24,
                    ),
                ),
                ("birth_date", models.DateField(default=None)),
                (
                    "ethnicity",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("AIFN", "American Indian/First Nations"),
                            ("BLAD", "Black/African Descent"),
                            ("EA", "East Asian"),
                            ("HL", "Hispanic/Latino"),
                            ("ME", "Middle Eastern"),
                            ("PI", "Pacific Islander"),
                            ("SA", "South Asian"),
                            ("SEA", "Southeast Asian"),
                            ("WC", "White/Caucasian"),
                            ("O", "Other"),
                        ],
                        max_length=1024,
                    ),
                ),
                (
                    "religion",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("AG", "Agnostic"),
                            ("A", "Atheist/None"),
                            ("B", "Buddhist"),
                            ("CA", "Catholic"),
                            ("C", "Christian"),
                            ("H", "Hindu"),
                            ("J", "Jewish"),
                            ("M", "Muslim"),
                            ("SK", "Sikh"),
                            ("SP", "Spiritual"),
                            ("O", "Other"),
                        ],
                        max_length=1024,
                    ),
                ),
                ("lgbtq", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="usergenre",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usergenre",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="usergenre",
            name="user",
        ),
        migrations.DeleteModel(
            name="BookGenre",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="UserGenre",
        ),
    ]
