# Generated by Django 4.1.2 on 2022-10-31 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookSwiping", "0013_alter_usergenre_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users_list",
            field=models.ManyToManyField(
                blank=True, related_name="books_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
