# Generated by Django 4.1.2 on 2022-11-04 14:42

from django.db import migrations
from django.contrib.postgres.operations import *


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0013_alter_usergenre_likes"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        BtreeGinExtension(),
        CITextExtension(),
    ]
