# Generated by Django 4.1.2 on 2022-10-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0014_book_users_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="users_list",
        ),
    ]
