# Generated by Django 4.1.2 on 2022-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0014_profile_alter_usergenre_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NYT_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list_name", models.CharField(max_length=256)),
                ("display_name", models.CharField(max_length=256)),
                ("update_schedule", models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="NYT_Lists",
            field=models.ManyToManyField(to="bookSwiping.nyt_list"),
        ),
    ]
