# Generated by Django 4.1.2 on 2022-11-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0015_nyt_list_book_nyt_lists"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="book",
        #     old_name="NYT_Lists",
        #     new_name="nyt_lists",
        # ),
    ]
