# Generated by Django 4.1.2 on 2022-10-31 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookSwiping", "0015_remove_book_users_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users_list",
            field=models.ManyToManyField(
                blank=True, related_name="books_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
