# Generated by Django 4.1.2 on 2022-10-31 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0016_book_users_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="users_list",
            new_name="users_liked_list",
        ),
    ]
