# Generated by Django 4.1.2 on 2022-11-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0014_auto_20221104_1042"),
        ("bookSwiping", "0017_rename_profile_userdemographics"),
    ]

    operations = []
