# Generated by Django 4.1.2 on 2022-11-07 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0017_rename_profile_userdemographics"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="book",
        #     old_name="nyt_lists",
        #     new_name="NYT_List",
        # ),
    ]
