# Generated by Django 4.1.2 on 2022-11-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0018_merge_20221107_1802"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="amazon_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
