# Generated by Django 4.1.2 on 2022-11-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0018_rename_nyt_lists_book_nyt_list"),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name="book",
        #     old_name="NYT_List",
        #     new_name="nyt_lists",
        # ),
    ]
