# Generated by Django 4.1.2 on 2022-11-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0019_rename_nyt_list_book_nyt_lists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="NYT_Lists",
        ),
        migrations.AddField(
            model_name="book",
            name="nyt_lists",
            field=models.ManyToManyField(to="bookSwiping.nyt_list"),
        ),
    ]
