# Generated by Django 4.1.2 on 2022-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0021_alter_userdemographics_ethnicity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdemographics",
            name="ethnicity",
        ),
        migrations.RemoveField(
            model_name="userdemographics",
            name="lgbtq",
        ),
        migrations.RemoveField(
            model_name="userdemographics",
            name="religion",
        ),
    ]
