# Generated by Django 4.1.2 on 2022-11-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0022_remove_userdemographics_ethnicity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="nyt_list",
            field=models.ManyToManyField(to="bookSwiping.nyt_list"),
        ),
    ]
