# Generated by Django 4.1.2 on 2022-11-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookSwiping", "0023_genre_nyt_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="nyt_list",
            field=models.ManyToManyField(blank=True, to="bookSwiping.nyt_list"),
        ),
    ]
