# Generated by Django 4.1.2 on 2022-12-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookSwiping", "0025_alter_userdemographics_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdemographics",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Book_Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("A", "Adult Content Visible to Children"),
                            ("I", "Information Missing"),
                            ("P", "Picture Missing"),
                        ],
                        default="I",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("O", "Open"),
                            ("R", "Closed - Resolved"),
                            ("N", "Closed - No Action Taken"),
                        ],
                        default="O",
                        max_length=24,
                    ),
                ),
                ("report_body", models.CharField(max_length=2056)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookSwiping.book",
                    ),
                ),
            ],
        ),
    ]
